# Generated by Django 4.1.1 on 2022-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
